export const environment = {
  production: true,
  platformProviderApiBaseUrl: 'https://fleetsafe-api.onrender.com/api/v1',
  platformProviderInspectionsEndpointPath: '/inspections',
  platformProviderInspectionItemsEndpointPath: '/inspection-items',
  platformProviderVehicleAssignmentEndpointPath: '/drivers/me/vehicle-assignment',
  platformProviderIncidentsEndpointPath: '/incidents',
  platformProviderIncidentTypesEndpointPath: '/incident-types',
  platformProviderRegisterCorrectiveActionEndpointPath: '/incidents',
  platformProviderScheduleRepairEndpointPath: '/incidents',
  platformProviderCompleteRepairEndpointPath: '/incidents',
  platformProviderAddIncidentFollowUpEndpointPath: '/incidents',
  platformProviderResolveIncidentEndpointPath: '/incidents',
  platformProviderCompaniesEndpointPath: '/companies',
  platformProviderFleetsEndpointPath: '/fleets',
  platformProviderVehiclesEndpointPath: '/vehicles',
  platformProviderDriversEndpointPath: '/drivers',
  platformProviderVehicleAssignmentsEndpointPath: '/vehicle-assignments',
};
