export enum ItemSystem {
  BRAKES = 'BRAKES',
  LIGHTS = 'LIGHTS',
  TIRES_AND_SUSPENSION = 'TIRES_AND_SUSPENSION',
  ENGINE_AND_FLUIDS = 'ENGINE_AND_FLUIDS',
  CABIN = 'CABIN',
  SAFETY_EQUIPMENT = 'SAFETY_EQUIPMENT',
  BODY_AND_COUPLING = 'BODY_AND_COUPLING',
  DOCUMENTATION = 'DOCUMENTATION',
}
